# Generated by Django 4.1.1 on 2022-12-03 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobsdb',
            name='service',
            field=models.CharField(blank=True, default='Eco meter', max_length=50, null=True),
        ),
    ]
