# Generated by Django 4.1.1 on 2022-12-04 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipmentList', '0001_initial'),
        ('jobs', '0002_jobsdb_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='equipment_job_activitiesdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assetnew', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipmentList.equipmentdb')),
                ('jobidnew', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.jobsdb')),
            ],
            options={
                'ordering': ['jobidnew'],
            },
        ),
    ]
