# Generated by Django 4.1.1 on 2022-12-04 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batteryList', '0003_alter_batterydb_in_service_date'),
        ('jobs', '0003_equipment_job_activitiesdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment_job_activitiesdb',
            name='battery',
            field=models.ManyToManyField(to='batteryList.batterydb'),
        ),
    ]
