# Generated by Django 4.1.1 on 2022-12-09 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_alter_equipment_job_activitiesdb_battery'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobsdb',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='jobs/%Y/%m/%d'),
        ),
    ]
