version: "3.9"
services:
  web:
    build: .
    ports:
      - "8000:8000"
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    env_file:
      - ./.env
    depends_on:
      - db
  # Below defind the database config and volumes
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    ports:
      - "5432:5432"
    # networks:
    #   app_net:
    #     ipv4_address: 192.168.0.2

    # Use below code to spin a pgadmin in docker and access the database
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: pgadmin4_container
    environment:
      - PGADMIN_DEFAULT_EMAIL=moh@hotmail.com
      - PGADMIN_DEFAULT_PASSWORD=1234
    ports:
      - "5050:80"
    volumes:
     - pgadmin-data:/var/lib/pgadmin
    # networks:
    #   app_net:
    #     ipv4_address: 192.168.0.3

volumes:
  postgres_data:
  pgadmin-data:

