# Generated by Django 4.1.1 on 2022-11-11 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='personneldb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('senionrty_date', models.DateField(blank=True)),
                ('birth_date', models.DateField(blank=True)),
                ('grade', models.DateField(blank=True)),
                ('position', models.DateField(blank=True)),
                ('department', models.DateField()),
            ],
            options={
                'ordering': ['first_name'],
            },
        ),
    ]
