# Generated by Django 4.1.1 on 2022-11-11 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personneldb',
            name='department',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='personneldb',
            name='grade',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='personneldb',
            name='position',
            field=models.CharField(max_length=255),
        ),
    ]
