# Generated by Django 4.1.1 on 2022-11-13 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0002_alter_personneldb_department_alter_personneldb_grade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personneldb',
            name='pdf_file',
            field=models.FileField(null=True, upload_to='pdfs/'),
        ),
    ]
