# Generated by Django 4.1.1 on 2022-11-05 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='equipmentdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_num', models.CharField(blank=True, max_length=200)),
                ('serial_num', models.CharField(blank=True, max_length=200, unique=True)),
                ('description', models.CharField(blank=True, max_length=800, null=True)),
                ('departement', models.CharField(blank=True, max_length=4, null=True)),
                ('asset_life', models.IntegerField(blank=True, null=True)),
                ('acquisition_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('acquisition_date', models.DateField(blank=True, null=True)),
                ('file_link', models.URLField(blank=True, null=True)),
            ],
            options={
                'ordering': ['serial_num'],
            },
        ),
    ]
