# Generated by Django 4.1.1 on 2022-12-08 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipmentList', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipmentdb',
            name='file_link',
        ),
        migrations.AddField(
            model_name='equipmentdb',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='equipment/'),
        ),
    ]
