# Generated by Django 4.1.1 on 2023-01-02 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='marketingdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_date', models.DateField(blank=True, null=True)),
                ('meeting_type', models.CharField(blank=True, max_length=200)),
                ('meeting_description', models.CharField(blank=True, max_length=800, null=True)),
                ('departement', models.CharField(blank=True, max_length=4, null=True)),
                ('client', models.CharField(blank=True, max_length=200, unique=True)),
                ('attendance', models.CharField(blank=True, max_length=200, unique=True)),
            ],
            options={
                'ordering': ['meeting_date'],
            },
        ),
    ]
