# Generated by Django 4.1.1 on 2023-01-03 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketingdb',
            name='attendance',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='marketingdb',
            name='client',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
