# Generated by Django 4.1.1 on 2022-12-08 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailyreport', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyreportdb',
            name='cmf',
        ),
        migrations.RemoveField(
            model_name='dailyreportdb',
            name='dp',
        ),
        migrations.RemoveField(
            model_name='dailyreportdb',
            name='flowduration',
        ),
        migrations.RemoveField(
            model_name='dailyreportdb',
            name='orifice',
        ),
        migrations.RemoveField(
            model_name='dailyreportdb',
            name='staticp',
        ),
        migrations.RemoveField(
            model_name='dailyreportdb',
            name='todayproduced',
        ),
        migrations.RemoveField(
            model_name='dailyreportdb',
            name='totalproduction',
        ),
        migrations.AddField(
            model_name='dailyreportdb',
            name='bhp',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='dailyreportdb',
            name='bht',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='dailyreportdb',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='dailyreports/'),
        ),
    ]
