# Generated by Django 4.1.1 on 2022-12-03 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('batteryList', '0001_initial'),
        ('equipmenMaintenance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batterymaintenancedb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_date', models.DateField()),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('ms_type', models.CharField(max_length=20, null=True)),
                ('voltage_value', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('battery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='batteryList.batterydb')),
            ],
            options={
                'ordering': ['check_date'],
            },
        ),
    ]
