# Generated by Django 4.1.1 on 2022-12-03 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='batterydb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_num', models.CharField(blank=True, max_length=40)),
                ('serial_num', models.CharField(blank=True, max_length=20, unique=True)),
                ('description', models.CharField(blank=True, max_length=400, null=True)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('in_service_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['serial_num'],
            },
        ),
    ]
