# Generated by Django 4.1.1 on 2022-12-03 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batteryList', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batterydb',
            name='in_service_date',
            field=models.DateField(null=True),
        ),
    ]
