# Generated by Django 4.1.1 on 2022-12-03 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batteryList', '0002_alter_batterydb_in_service_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batterydb',
            name='in_service_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
