# Generated by Django 4.1.1 on 2022-12-08 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batteryList', '0003_alter_batterydb_in_service_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='batterydb',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='batteries/'),
        ),
    ]
