# Generated by Django 4.1.1 on 2022-12-09 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_remove_trainingdb_person_trainingdb_attendees'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingdb',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='training/%Y/%m/%d'),
        ),
    ]
